version: 6.0.0
variant: default
logo: /images/blog/logo.png
head:
    favicon: /images/blog/ava.png
    manifest:
        name: 
        short_name: 
        start_url: 
        theme_color: 
        background_color: 
        display: standalone
        icons:
            -
                src: ''
                sizes: ''
                type: 
    open_graph:
        title: 
        type: blog
        url: 
        image: 
        site_name: 
        author: 
        description: 
        twitter_card: 
        twitter_id: 
        twitter_site: 
        google_plus: 
        fb_admins: 
        fb_app_id: 
    structured_data:
        title: 
        description: 
        url: 
        author: 
        publisher: 
        publisher_logo: 
        image: 
    meta:
        - ''
    rss: 
navbar:
    menu:
        首页: /
        时间线: /archives
        分类: /categories
        关于: /about
        醍醐灌顶: /sentences
        anpu - 與你握手: /anpu
footer:
    links:
        Creative Commons:
            icon: fab fa-creative-commons
            url: https://creativecommons.org/
        Attribution 4.0 International:
            icon: fab fa-creative-commons-by
            url: https://creativecommons.org/licenses/by/4.0/
        Download on GitHub:
            icon: fab fa-github
            url: https://github.com/ppoffice/hexo-theme-icarus
toc: true
article:
    highlight:
        theme: atom-one-light
        clipboard: true
        fold: unfolded
    readtime: false
    update_time: false
search:
    type: insight
sidebar:
    left:
        sticky: false
    right:
        sticky: false
widgets:
    -
        position: left
        type: profile
        author: Jerry Sheh
        author_title: 车顶上绑着飞机发动机
        location: Shenzhen
        avatar: /images/blog/ava.png
        gravatar: 
        avatar_rounded: false
        follow_link: mailto:jerrysheh@gmail.com
        social_links:
            Github:
                icon: fab fa-github
                url: https://github.com/Jerrysheh
            email:
                icon: fa fa-envelope
                url: mailto:jerrysheh@gmail.com
    -
        position: right
        type: toc
        index: true
        collapsed: false
        depth: 3
    -
        position: right
        type: links
        links:
            我没有三颗心脏: https://www.wmyskxz.com/
            Vamei: https://www.cnblogs.com/vamei/
            celesteheadlee: https://www.celesteheadlee.com/
            Baron Schwartz: https://www.xaprb.com/
            jenkov: http://tutorials.jenkov.com/
            安溥 anpu: https://www.anpu-oystermusic.com/
    -
        position: left
        type: categories
plugins:
    animejs: true
    back_to_top: true
    baidu_analytics:
        tracking_id: 
    bing_webmaster:
        tracking_id: 
    busuanzi: true
    cnzz:
        id: 
        web_id: 
    cookie_consent:
        type: info
        theme: edgeless
        static: false
        position: bottom-right
        policyLink: https://www.cookiesandyou.com/
    gallery: true
    google_analytics:
        tracking_id: 
    hotjar:
        site_id: 
    katex: false
    mathjax: false
    outdated_browser: false
    progressbar: true
    statcounter:
        project: 
        security: 
    twitter_conversion_tracking:
        pixel_id: 
